name: Build and Deploy to Azure Container Apps

on:
  push:
    branches: [ "db-app" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.ITINERARY_GHCR_USERNAME }}
          password: ${{ secrets.ITINERARY_GHCR_TOKEN }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: db-app
          file: db-app/Dockerfile
          push: true
          tags: ghcr.io/gphang/db-app:latest

    #   - name: Log in to Azure
    #     run: |
    #       az login --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }}
    #   - name: Update Azure Container App
    #     run: |
    #       az containerapp update \
    #         --name db-app \
    #         --resource-group tether-rg-2 \
    #         --image ghcr.io/gphang/db-app:latest \