name: Build and Deploy to Azure Container Apps

on:
  push:
    branches: [ "flight-app" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r flight-app/requirements.txt

      - name: Run unit tests
        run: |
            cd flight-app
            pytest tests --maxfail=1 --disable-warnings -q

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.FLIGHT_GHCR_USERNAME }}
          password: ${{ secrets.FLIGHT_GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: flight-app
          file: flight-app/Dockerfile
          push: true
          tags: ghcr.io/zjx047/flight-app:latest

      # - name: Log in to Azure CLI
      #   uses: azure/login@v1
      #   with:
      #     creds: |
      #       {
      #         "clientId": "${{ secrets.AZURE_USERNAME }}",
      #         "clientSecret": "${{ secrets.AZURE_PASSWORD }}",
      #         "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
      #         "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      #       }

      # - name: Update Azure Container App
      #   run: |
      #     az containerapp update \
      #       --name flight-app \
      #       --resource-group tether-rg-2 \
      #       --image ghcr.io/zjx047/flight-app:latest \