name: Build and Deploy to Azure Container Apps

on:
  push:
    branches: [ "weather-app" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.WEATHER_GHCR_USERNAME }}
          password: ${{ secrets.WEATHER_GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: weather-app
          file: weather-app/Dockerfile
          push: true
          tags: ghcr.io/atchyuni/weather-app:latest
      
      - name: Log in to Azure
        run: |
          az login --identity
      
      - name: Update Azure Container App
        run: |
          az containerapp update \
            --name weather-app \
            --resource-group tether-rg-2 \
            --image ghcr.io/atchyuni/weather-app:latest