name: Build and Deploy to Azure Container Apps

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: weather-app
          file: weather-app/Dockerfile
          push: true
          tags: ghcr.io/atchyuni/weather-app:latest

      - name: Azure CLI - set up
        uses: azure/cli@v1
        with:
          azcliversion: latest

      - name: Log in to Azure
        run: |
          az login --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }}

      - name: Update Azure Container App
        run: |
          az containerapp update \
            --name weather-app \
            --resource-group tether-rg-2 \
            --image ghcr.io/atchyuni/weather-app:latest \
            --registry-server ghcr.io \
            --registry-username ${{ secrets.GHCR_USERNAME }} \
            --registry-password ${{ secrets.GHCR_TOKEN }}
